const motiversity = [
  '"Amateurs sit and wait for inspiration, the rest of us just get up and go to work." — Stephen King',
  '"You don\'t get paid for the hour. You get paid for the value you bring to the hour." — Jim Rohn',
  '"Discipline is doing what you hate to do, but nonetheless doing it like you love it." — Mike Tyson',
  '"The distance between your dreams and reality is called action." — Unknown',
  '"If you want to buy things without looking at the price, work without looking at the clock." — Unknown',
  '"You are exactly where you deserve to be based on the actions you haven\'t taken." — Unknown',
  '"Don\'t stop when you\'re tired. Stop when you\'re done." — David Goggins',
  '"Systems scale. Motivation doesn\'t. Build the system." — Unknown',
  '"The hard days are the best because that\'s when champions are made." — Gabby Douglas',
  '"Success is rented, and the rent is due every single day." — Rory Vaden',
  '"If people aren\'t calling you crazy, you aren\'t thinking big enough." — Richard Branson',
  '"Be so good they can\'t ignore you." — Steve Martin',
  '"The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity." — Ryan Holiday',
  '"Engineers don\'t complain about the laws of physics, they build around them. Stop complaining about the market." — Unknown',
  '"You can\'t build a reputation on what you are going to do." — Henry Ford',
  '"Do what you have to do until you can do what you want to do." — Oprah Winfrey',
  '"A lead is just an unsolved problem. Go solve it." — Unknown',
  '"The master has failed more times than the beginner has even tried." — Stephen McCranie',
  '"Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones." — Benjamin Franklin',
  '"Don\'t wish it was easier, wish you were better." — Jim Rohn',
  '"I hated every minute of training, but I said, \'Don\'t quit. Suffer now and live the rest of your life as a champion.\'" — Muhammad Ali',
  '"We suffer more often in imagination than in reality." — Seneca',
  '"It is not the critic who counts; the credit belongs to the man who is actually in the arena." — Theodore Roosevelt',
  '"You do not rise to the level of your goals. You fall to the level of your systems." — James Clear',
  '"Outwork your self-doubt." — Unknown',
  '"Action cures fear." — David Schwartz',
  '"The successful warrior is the average man, with laser-like focus." — Bruce Lee',
  '"If you are going through hell, keep going." — Winston Churchill',
  '"Opportunities don\'t happen. You create them." — Chris Grosser',
  '"Greatness is a lot of small things done well every day." — Ray Lewis',
  '"You can\'t hire someone to do the push-ups for you." — Jim Rohn',
  '"It is impossible for a man to learn what he thinks he already knows." — Epictetus',
  '"Focus on the lead measure (doors knocked), not the lag measure (closings)." — Chris McChesney',
  '"I have never met a heavy lifter with a light wallet." — Unknown',
  '"If it comes easy, it will go fast." — Andrena Sawyer',
  '"Nobody cares, work harder." — Cameron Hanes',
  '"Obsession is the word the lazy use to describe the dedicated." — Russell Warren',
  '"The only difference between a good day and a bad day is your attitude." — Dennis S. Brown',
  '"Work like there is someone working 24 hours a day to take it all away from you." — Mark Cuban',
  '"Doubt is only removed by action. If you\'re not working then that\'s where doubt comes in." — Conor McGregor',
  '"You can have results or excuses. Not both." — Arnold Schwarzenegger',
  '"Don\'t count the days, make the days count." — Muhammad Ali',
  '"Motivation is what gets you started. Habit is what keeps you going." — Jim Ryun',
  '"Someday is a disease that will take your dreams to the grave with you." — Timothy Ferriss',
  '"The wolf on the hill is never as hungry as the wolf climbing the hill." — Arnold Schwarzenegger',
  '"Volume negates luck." — Alex Hormozi',
  '"If you want to be in the 1%, you can\'t do what the 99% do." — Unknown',
  '"The pain of discipline is nothing like the pain of disappointment." — Justin Langer',
  '"If you are not willing to risk the usual, you will have to settle for the ordinary." — Jim Rohn',
  '"Hard work beats talent when talent doesn\'t work hard." — Tim Notke',
  '"I am not a product of my circumstances. I am a product of my decisions." — Stephen Covey',
  '"It\'s what you do in the dark that puts you in the light." — Under Armour',
  '"Nothing works unless you do." — Maya Angelou',
  '"The only place where success comes before work is in the dictionary." — Vidal Sassoon',
  '"I find that the harder I work, the more luck I seem to have." — Thomas Jefferson',
  '"Do not wait; the time will never be \'just right.\'" — George Napoleon Hill',
  '"Everything you\'ve ever wanted is sitting on the other side of fear." — George Addair',
  '"Success is not final; failure is not fatal: It is the courage to continue that counts." — Winston S. Churchill',
  '"You don\'t have to be great to start, but you have to start to be great." — Zig Ziglar',
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"What you do today can improve all your tomorrows." — Ralph Marston',
  '"Don\'t watch the clock; do what it does. Keep going." — Sam Levenson',
  '"Whether you think you can or you think you can\'t, you\'re right." — Henry Ford',
  '"You miss 100% of the shots you don\'t take." — Wayne Gretzky',
  '"I failed my way to success." — Thomas Edison',
  '"It always seems impossible until it\'s done." — Nelson Mandela',
  '"The future depends on what you do today." — Mahatma Gandhi',
  '"To achieve what 1% of the world\'s population has, you must be willing to do what only 1% dare to do." — Manoj Arora',
  '"There are no traffic jams on the extra mile." — Zig Ziglar',
  '"The elevator to success is out of order. You\'ll have to use the stairs, one step at a time." — Joe Girard',
  '"People often say that motivation doesn\'t last. Well, neither does bathing - that\'s why we recommend it daily." — Zig Ziglar',
  '"I attribute my success to this: I never gave or took any excuse." — Florence Nightingale',
  '"Eighty percent of success is showing up." — Woody Allen',
  '"Success usually comes to those who are too busy to be looking for it." — Henry David Thoreau',
  '"Don\'t let the fear of losing be greater than the excitement of winning." — Robert Kiyosaki',
  '"If you really look closely, most overnight successes took a long time." — Steve Jobs',
  '"I cannot give you the formula for success, but I can give you the formula for failure: It is: Try to please everybody." — Herbert Bayard Swope',
  '"The real test is not whether you avoid this failure, because you won\'t. It\'s whether you let it harden or shame you into inaction." — Barack Obama',
  '"You learn more from failure than from success. Don\'t let it stop you. Failure builds character." — Unknown',
  '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
  '"Quality is not an act, it is a habit." — Aristotle',
  '"Do or do not. There is no try." — Yoda',
  '"It\'s not about better time management. It\'s about better life management." — Alexandra of Denmark',
  '"First forget inspiration. Habit is more dependable. Habit will sustain you whether you\'re inspired or not." — Octavia Butler',
  '"Good things happen to those who hustle." — Anaïs Nin',
  '"You only live once, but if you do it right, once is enough." — Mae West',
  '"May your choices reflect your hopes, not your fears." — Nelson Mandela',
  '"Whatever you are, be a good one." — Abraham Lincoln',
  '"Fall seven times and stand up eight." — Japanese Proverb',
  '"The best revenge is massive success." — Frank Sinatra',
  '"The only way to do great work is to love what you do." — Steve Jobs',
  '"Strive not to be a success, but rather to be of value." — Albert Einstein',
  '"Definiteness of purpose is the starting point of all achievement." — W. Clement Stone',
  '"We become what we think about." — Earl Nightingale',
  '"Your time is limited, so don\'t waste it living someone else\'s life." — Steve Jobs',
  '"Life is 10% what happens to me and 90% of how I react to it." — Charles Swindoll',
  '"The mind is everything. What you think you become." — Buddha',
  '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
  '"An unexamined life is not worth living." — Socrates',
  '"Winning isn\'t everything, but wanting to win is." — Vince Lombardi'
];
